name: Auto Actualización Global

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Ejecutar sistema de defensa
        run: |
          python defensa.py
          node sistema.js
